MANIFEST.in
README.md
pyproject.toml
setup.py

This change improves the diagnostics from setup.py. A new helpful
error messages will trigger if any dependencies are missing when
installing the package. This typically happens when PIP version is <19
and the user is missing the build dependencies.
Example error message:
Missing module 'skbuild'. Please install 'scikit-build' manually
or use PIP>=19 to handle build dependencies automatically (PEP
517).
Version number is bumped to 0.9.1 and this version will be uploaded to
PyPI.
The README.md is now simplified to not use venv since we gracefully
handle older PIP version. It is also updated to install the package
from PyPI and not git.
The Versioning section of README.md is extended to explain what all
those digits in the module version is all about.

Make using old PIP easier

---

doc/CompilerInstallation.md

I finally found the correct place to download old version of Visual Studio.

Improved documentation with direct link to VS 2017

---

modules/_zivid/__init__.py

The stacktrace from `import zivid` will now look like this:
```
Traceback (most recent call last):
File "/tmp/env/lib/python3.7/site-packages/_zivid/__init__.py", line 3, in <module>
from _zivid._zivid import (  # pylint: disable=import-error,no-name-in-module
ImportError: libZividCore.so: cannot open shared object file: No such file or directory
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/env/lib/python3.7/site-packages/zivid/__init__.py", line 8, in <module>
from zivid.application import (
File "/tmp/env/lib/python3.7/site-packages/zivid/application.py", line 2, in <module>
import _zivid
File "/tmp/env/lib/python3.7/site-packages/_zivid/__init__.py", line 23, in <module>
) from ex …
```

Raise a customized nested exception when _zivid fails at import

---

azure-pipelines.yml

Build the master branch nightly will ensure that we will quickly detect
if master is broken or not.

Enable nightly build

---

test/conftest.py

We can enable redefined-out-name from test/conftest.py by giving the
fixtures a name through the @pytest.fixture decorator.

Removed pylint disable redefined-out-name in conftest

---

.flake8-packaged-files
modules/zivid/__init__.py
modules/zivid/frame.py
modules/zivid/point_cloud.py
src/CMakeLists.txt
src/ReleasablePointCloud.cpp
src/Wrapper.cpp
src/include/ZividPython/PointCloud.h
src/include/ZividPython/Releasable.h
src/include/ZividPython/ReleasableFrame.h
src/include/ZividPython/ReleasablePointCloud.h
src/include/ZividPython/Wrappers.h
test/conftest.py
test/test_frame.py
test/test_point_cloud.py

Instead of transforming the point cloud directly to a numpy buffer, we
should instead return a intermediate layer, since in the underlying C++
API point cloud exposes various functions such as width and height.
Making buffer releasable also created some technical debt:
assertNotReleased is needed since accessing the underlying a C++ object
after it has been released causes a crash.

Releaseable point cloud

---

modules/_zivid/__init__.py
modules/zivid/__init__.py
modules/zivid/_settings_2d_converter.py
modules/zivid/camera.py
modules/zivid/frame_2d.py
modules/zivid/image.py
modules/zivid/settings_2d.py
samples/sample_capture_2d.py
src/CMakeLists.txt
src/ReleasableCamera.cpp
src/ReleasableFrame2D.cpp
src/ReleasableImage.cpp
src/Wrapper.cpp
src/include/ZividPython/Releasable.h
src/include/ZividPython/ReleasableCamera.h
src/include/ZividPython/ReleasableFrame2D.h
src/include/ZividPython/ReleasableImage.h
test/conftest.py
test/test_camera.py
test/test_frame_2d.py
test/test_image_2d.py
test/test_settings_2d.py

Enables 2D API in this wrapper, so that you can easily capture 2D images
using a camera. 2D sample capture and tests has been included.

2D API wrapper

---

setup.py

Bumping version so we can release a new version to PYPI but still build against Zivid SDK 1.7.0. This release will contain HandEye API and 2D API.

Version number is bumped to 0.9.2

---

README.md
setup.py

- Changed instructions in README to refer directly to pyproject.toml.
This avoids the possibility of the instructions becoming out of sync.
- Adjusted _check_dependency() to avoid printing "None", like:
"Missing module 'cmake'. Please install 'None' manually or..."
- Added comment explaining why conan cannot be checked by
_check_dependency().

Adjust README and setup.py

---

pyproject.toml
setup.py

This improve error messages during `pip install zivid` on systems
without binary packages and without C++17 support. This is implemented
as a nested exceptions where the outer most excetion gives a fix-it
hint.
I also sorted some dependency lists.
**Before**
**After**

Improve error message when module build does not work

---

.github/CODEOWNERS

This patch sets the following uses as global code owners:
* nedrebo
* trym-b
* eskaur
When this is merged we will also require review from code owners when
making a pull request(PR) to master. This is done to because the
customer success team is now given write access to the repository to
be able to easily fix minor issues. However I want to restrict who can
approve PRs to master.
This change also gives us experience with the code owners feature, it
is likely something we want to enable for more repositories.

Enabling GitHub code owners feature for repository

---

continuous-integration/linux/platform-dependent/arch/setup.sh
continuous-integration/linux/platform-dependent/common.sh
continuous-integration/linux/platform-dependent/fedora-30/setup.sh
continuous-integration/linux/platform-dependent/ubuntu-16.04/setup.sh
continuous-integration/linux/platform-dependent/ubuntu-18.04/setup.sh
continuous-integration/linux/setup.sh
src/include/ZividPython/Releasable.h

Since updating zivid AUR packages, the current master does no longer
build on arch. Pinning the version makes arch build again.
This is required to get zivid-python to pass CI before the wrapper is
updated to work with API 2.0.
Also updated OpenCL setup in order not to fail when run in the CI.

Pin arch AUR zivid package version and fix broken OpenCL test setup

---

continuous-integration/linux/platform-dependent/arch/setup.sh
continuous-integration/linux/platform-dependent/common.sh
continuous-integration/linux/platform-dependent/fedora-30/setup.sh
continuous-integration/linux/platform-dependent/ubuntu-16.04/setup.sh
continuous-integration/linux/platform-dependent/ubuntu-18.04/setup.sh
continuous-integration/linux/setup.sh

The CI tests have been failing frequently with the following error:
> An OpenCL error occurred: Failed to get devices for context.
> ...
> [CL_INVALID_CONTEXT]
After some digging into this using clinfo, I discovered that device
name like "Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz" fails, while
"Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz" works. This suggests that
our current Intel OpenCL CPU driver does not support all the CPU's
available in Azure Pipelines.
Updating the Intel driver from version 16.1.1 to 18.1.0 fixes this
problem.
The prior method of manually installing the OpenCL CPU driver based on
the .tgz archive caused problems (clinfo would just hang). From this
commit we are instead using the install.sh script provided by Intel.
We now also print out "clinfo" after installing …

Fix broken CI tests with updated Intel OpenCL CPU driver

---

azure-pipelines.yml
continuous-integration/linux/platform-dependent/ubuntu-20.04/setup.sh

This commit ensures that zivid-python is built and tested on the latest
LTS version of Ubuntu, using the same Zivid SDK artifacts as Ubuntu
18.04.

Enable Ubuntu 20.04 tests

---

continuous-integration/windows/setup.py
continuous-integration/windows/test.py
test/test_samples.py

In order to run tests on Windows, Intel OpenCL runtime needs to be
installed to run the tests on a compute device. It is also required to
create a configuration file so that the tests are run on the CPU instead
of a GPU (since there are no GPU available in azure-pipelines)
Added update environment script in order to load the latest envrionement
variables set by `Zivid-SDK` after successful installation. `PATH`
environment variable must be updated befre running the tests.
Ignored sample testing for windows, because of the following error:
```
python: can't open file 'D:\a\samples\sample_print_version_info.py': [Errno 2] No such file or directory
```
Ignored `winreg` import error, this module is not available on Linux

Enable Windows CI tests

---

continuous-integration/windows/test.py

It is possible that calling pip directly does not install packages for the Python accessed with Python directly. To avoid mismatch, call pip via Python.
`python -m pip install -r requirements.txt`
vs
`pip install -r requirements.txt`

Avoid mismatch in Python version

---

test/conftest.py
test/test_samples.py

Resolves #82
See #84 for future work.

Test samples on Windows

---

continuous-integration/python-requirements/lint.txt
continuous-integration/python-requirements/test.txt

* `darglint` from 1.4.1 to 1.5.3
* `pylint` from 2.5.3 to 2.6.0
* `pytest` from 5.4.3 to 6.0.1
* `pytest-timeout` from 1.4.1 to 1.4.2

Bump pip packages

---

modules/zivid/application.py
modules/zivid/camera.py
modules/zivid/frame.py
modules/zivid/frame_2d.py
modules/zivid/image.py
modules/zivid/point_cloud.py

Currently, if e.g. a PointCloud gets scheduled for deletion before
self.__impl has been set (e.g. due to an error in __init__),
an AttributeError would be thrown from __del__. Exceptions are
ignored when coming from __del__, but may still cause an error
message to be written to stderr, which looks bad.
The problem can be illustrated by running:
```
pytest -c ./pytest.ini test/test_point_cloud.py --capture=no -k test_illegal_init
```
This commit solves this by checking that self.__impl exists before
calling release() on it.

Fix errors from __del__ methods

---

src/ReleasableArray2D.cpp
src/ReleasableImage.cpp

Windows compilers complained about some implicit casting being done
in ReleaseableImage.cpp/ReleasableArray2D.cpp.

Fix Windows build

---

test/calibration/test_hand_eye.py

The reference matrix was based on a Linux run, and the outcome of this
algorithm seems to be a bit sensitive to the compiler/platform (since
the test-dataset has quite few poses). Changing the tolerance to let
this pass test on Windows.

Decrease precision requirement of hand-eye test

---

README.md

We do not actually support Python 3.5 on Windows (and never have),
so we should remove it from the test-matrix in the Readme.

Readme: Remove 3.5 from Windows row in test matrix

---

modules/zivid/firmware.py

The "Args" entries in the docstrings of update() and is_up_to_date()
were misleading. This commit fixes that.
Resolves Issue #4

Issue #4: Fix firmware docstrings

---

modules/zivid/_calibration/detector.py
src/Calibration/Detector.cpp
src/include/ZividPython/Matrix.h
test/calibration/test_calibration_basics.py

A small new feature that was introduced in SDK 2.2,
DetectionResult.centroid(), was not included in the corresponding
release of zivid-python. This commit add that feature.

Add DetectionResult.centroid()

---

.github/workflows/main.yml
README.md
continuous-integration/linux/platform-dependent/fedora-33/setup.sh
doc/CompilerInstallation.md

This commit adds Fedora33 to the CI test matrix, which means that we now
officially support/test python3.9 on Linux. We already supported
python3.9 on Windows.

Add Fedora33 (python3.9) to CI test matrix

---

.github/workflows/main.yml

Can be reverted after these issues are fixed.
https://github.com/actions/virtual-environments/issues/2658
https://github.com/moby/moby/pull/42014

CI: Use runc v1.0.0-rc93 on hosts with archlinux containers

---

src/include/ZividPython/Traits.h
src/include/ZividPython/Wrappers.h

The classes in the calibration API have the following implementation on
the front-end,
```
def __bool__(self):
return bool(self.__impl)
```
which was intended to represent the corresponding boolean operator on
the C++ API level. However, the boolean operator of the `__impl`s were
never overridden on the Pybind11 level, so they instead defaulted to
some behavior that seemingly always returns True, and is independent of
the `operator bool` in the C++ API. This caused the following kind of
bugs in the Python API
```
detection_result.valid() # False
bool(detection_result)   # True
```
This commit fixes this by explicitly hooking up the `__bool__` of the
Pybind11-generated classes to the `operator bool` of the C++ classes.
This yields behavior that is identical to the C++ API, as intended.
No …

Fix bug where __bool__ -> True when valid() -> False

---

.github/workflows/main.yml

Previously, if someone forked this repo and created a pull request from
that external repo, Github Actions would not be triggered. This makes it
difficult to know if the external changes will break this repo or not.
This commit ensures that external PRs now will trigger CI builds.

CI: Enable CI for external pull requests

---

.github/workflows/main.yml

The reverted commit caused two builds whenever you pushed with a PR
open, which I had hoped would not happen.
This reverts commit dc0b8b8848a68b9a61b53e4938adfe70a5080a5e.

Revert "CI: Enable CI for external pull requests"

---

src/include/ZividPython/DataModelWrapper.h
src/include/ZividPython/Wrappers.h

This function does not modify its string argument,
i.e. can use std::string_view, assuming C++17.
This avoids implicit std::string temporaries.
Also fixes a use-after-free of the form:
toSnakeCase(name).c_str()
This aligns the function with the one in SDK,
including a couple of unrelated changes:
* Loop variable type: int → size_t (would satisfy gcc -Wsign-compare)
* The call to tolower can be made unconditional due to idempotence.
Implements #93

DataModelWrapper::toSnakeCase: Take string_view #132

---

.github/workflows/main.yml
continuous-integration/notification/notify_teams.py

Notify Teams channel on the `secrets.CI_FAILURE_TEAMS_HOOK` webhook url
if a job in the CI workflow fails.
---
Here's an example of the notification one will get if the `lint` job in the CI
workflow fails.

Notify Teams channel upon CI failure

---

CMakeLists.txt
src/CMakeLists.txt

Previously eigen was provided by this repo:
https://github.com/conan-community/conan-eigen
Now it has been moved to: https://github.com/conan-io/conan-center-index
Also bumped eigen from 3.3.7 to 3.3.9.
Special thanks to @erikschuitema for providing this fix.
Closes #139

Eigen: Bump version to 3.3.9

---

.pylintrc
.pylintrc-internal
.pylintrc-tests
continuous-integration/python-requirements/lint.txt
continuous-integration/windows/common.py
modules/zivid/camera.py
modules/zivid/capture_assistant.py
modules/zivid/frame.py
modules/zivid/frame_2d.py
samples/sample_calibrate_eye_to_hand.py
setup.py

This commit does the following:
- Bump linting tools with `pip-compile --upgrade`.
- Update code to conform with new rules.
We ignore the "consider-using-f-string" rule because we do not want to
intentionally break the unofficial support for Ubuntu 16.04 / python3.5
yet. (f-strings were introduced in python3.6)

Bump linting tools

---

doc/CompilerInstallation.md

I noticed the Fedora compiler installation instructions were out of date.
Instead of adding the missing versions, I opted to remove all the
versions to reduce the risk of similar regressions in the future.

Minor readme fix

---

continuous-integration/python-requirements/build.txt

Without this commit the CI is broken, the error we got was
```
ERROR: Not able to automatically detect 'cl.exe' version
ERROR: Unable to find a working compiler
WARN: Remotes registry file missing, creating default one in C:\Users\runneradmin\.conan\remotes.json
ERROR: eigen/3.3.9: Cannot load recipe.
Error loading conanfile at 'C:\Users\runneradmin\.conan\data\eigen\3.3.9\_\_\export\conanfile.py': Current Conan version (1.40.3) does not satisfy the defined one (>=1.43.0).
```
By bumping the conan version this issue is now fixed.

Bump python dependencies

---

.flake8
.pylintrc
.pylintrc-internal
continuous-integration/code-generation/datamodel_frontend_generator.py
modules/_zivid/__init__.py
modules/zivid/__init__.py
modules/zivid/camera_intrinsics.py
modules/zivid/experimental/calibration.py
setup.py
src/Calibration/Calibration.cpp
test/calibration/test_intrinsics.py

This commit expands the Python wrapper to give access to the
experimental camera intrinsics API. This entails two new functions:
```
from zivid.experimental.calibration import intrinsics
from zivid.experimental.calibration import estimate_intrinsics
```
As part of this the CameraIntrinsics data-model also needs to be
wrapped. Since this data-model (as opposed to the above mentioned
functions) is not technically experimental in the C++ API, it is not
added as experimental here either.
This resolves Issue #42

Add experimental camera intrinsics API

---

modules/_zivid/__init__.py
modules/zivid/experimental/calibration.py
samples/sample_infield_correction.py
samples/sample_infield_verification.py
src/CMakeLists.txt
src/InfieldCorrection/InfieldCorrection.cpp
src/Wrapper.cpp
src/include/ZividPython/InfieldCorrection/InfieldCorrection.h

This commit extends zivid-python to wrap the existing experimental C++
"in-field correction/verification" API:
<https://support.zivid.com/latest/academy/camera/infield-correction.html>
See the two new samples for a demonstration of usage:
`samples/sample_infield_verification.py`
`samples/sample_infield_correction.py`

Add in-field correction/verification API

---

.github/workflows/main.yml
README.md
continuous-integration/linux/platform-dependent/fedora-35/setup.sh

Unit-testing on fedora35 and archlinux was previously removed due to a
bug. The bug has been fixed, so we can re-enable it.
Fixes #161

Re-enable unit-testing on fedora35 and archlinux

---

README.md

Installing `zivid-python` on Ubuntu only works if `python3-dev` is installed, and
this package is not installed by default. While we do this in the CI setup scripts, 
there was no mention of this in the README. This commit adds such a mention.

Update README to include hint about python3-dev

---

modules/_zivid/__init__.py
modules/zivid/__init__.py
modules/zivid/matrix4x4.py
samples/sample_calibrate_eye_to_hand.py
src/CMakeLists.txt
src/Matrix4x4.cpp
src/Wrapper.cpp
src/include/ZividPython/Matrix4x4.h
src/include/ZividPython/Wrappers.h
test/calibration/test_hand_eye.py
test/calibration/test_multi_camera.py
test/test_matrix4x4.py

The Matrix4x4 API is largely similar to that of the native C++ version. But the Matrix4x4 objects are convertible to and from numpy.ndarray:
```
matrix = zivid.Matrix4x4(...)
numpy_array = numpy.array(matrix)
matrix = zivid.Matrix4x4(numpy_array)
```
All our API functions that work with numpy arrays also work with zivid.Matrix4x4. In addition, all numpy functions that expect numpy.ndarray of float32[4, 4] also work with zivid.Matrix4x4.

Expose Zivid::Matrix4x4 to the Python bindings 

---

.github/workflows/main.yml
CMakeLists.txt
README.md
continuous-integration/deployment/expected-artifacts.txt
continuous-integration/linux/lint.sh
continuous-integration/linux/test.sh
continuous-integration/python-requirements/legacy-python36/test.in
continuous-integration/python-requirements/legacy-python36/test.txt
continuous-integration/python-requirements/lint.in
continuous-integration/python-requirements/lint.txt
licenses-dependencies/python311.txt
pytest.ini
test/test_matrix4x4.py

This commit adds Windows+Python3.11 to the CI workflow, which means that a `.whl` file for that system is built and tested.
Supporting Python 3.11 required the following changes:
- Bump `pybind11`  to version 2.10.0
- Bump `pytest` to version 7.2
- Remove `pytest-pythonpath` since it is deprecated and no longer needed
- Bump `black` to version 22 to keep compatible with new `pytest`.
Since Python 3.6 has been end-of-life since December 2021, we remove the Windows+Python3.6 combination at the same time. An exception is made for Ubuntu 18.04 (which has Python 3.6 as its default Python), since Ubuntu 18.04 is not yet end-of-life. Unfortunately the new `pytest` is not compatible with Python 3.6, so we had to make a separate "legacy" version of `test.txt` requirements file for this CI job.

Build and test for Windows+Python3.11

---

README.md

Listing the SDK version in the test matrix is not really useful. Each commit of `zivid-python` supports exactly one version of the SDK, and that version is stated further up in the README anyway. Simplifying this will reduce the manual work of bumping the supported SDK version.

Simplify test matrix table

---

.github/workflows/main.yml

The CI workflow has been getting deprecation warnings lately because we use older version of standard actions that use Node.js 12. This commit updates all the standard actions to resolve this issue.

Update standard actions to latest versions

---

continuous-integration/linux/platform-dependent/common.sh
continuous-integration/linux/platform-dependent/fedora-30/setup.sh
continuous-integration/linux/platform-dependent/fedora-33/setup.sh
continuous-integration/linux/platform-dependent/fedora-34/setup.sh
continuous-integration/linux/platform-dependent/fedora-35/setup.sh
continuous-integration/linux/platform-dependent/ubuntu-18.04/setup.sh
continuous-integration/linux/platform-dependent/ubuntu-20.04/setup.sh
continuous-integration/linux/platform-dependent/ubuntu-22.04/setup.sh
continuous-integration/versions.json
continuous-integration/windows/setup.py

Version strings like `2.8.1+dd4dffea-1` are used to choose which SDK installers are downloaded in the CI worflows. These were unnecessarily duplicated across many files. This commit defines them in a single place, so that future commits that bumps SDK version can be simpler.

De-duplicate exact SDK version used in CI

---

continuous-integration/linux/platform-dependent/arch/setup.sh

Recently, new versions of the Arch AUR packages for SDK 2.9 were uploaded. These packages reference the new `downloads.zivid.com` domain instead of the temporary one.
This commit updates the CI in the zivid-python repo to use those new AUR packages, so that we do not need to maintain the temporary URLs.

Update Arch AUR package references

---

modules/zivid/frame_2d.py
src/ReleasableFrame2D.cpp
src/include/ZividPython/ReleasableFrame2D.h
test/test_frame_2d.py

In SDK 2.9 `Frame2D` was extended with a `CameraInfo` getter, similar to what `Frame` already had. This commit exposes this to zivid-python.

Add `Frame2D.camera_info` property

---

test/conftest.py
test/test_camera.py
test/test_frame_2d.py
test/test_image_2d_bgra.py
test/test_image_2d_rgba.py

Previously all unit-tests that depend on 2D capture were marked with `@pytest.mark.physical_camera` because at some point in the past 2D captures did not work with file cameras. Such tests are not run in the CI because the CI does not have access to real cameras.  The intended procedure was that developers would run pytest with `-m physical_camera` before making a PR. However this is a vulnerable system because:
- Developers may forget or not know that they should do this.
- Even if they do this, they are unlikely to do it on all supported platforms. So it was possible to merge changes to 2D capture API that for example does not work on Python 3.6.
In the latest SDK release it is not a problem to do 2D captures with file cameras. Thus we can close this pitfall by making all the 2D capture …

Start testing 2D capture API in the CI

---

samples/sample_capture_async.py
src/include/ZividPython/Releasable.h

This unlocks GIL during captures so they can be executed in parallel. This also adds a sample to show how to execute captures in parallel.
Implements ZIVID-6981

Capture: Unlock GIL during capture to allow async

---

README.md
samples/sample_capture_from_file.py
test/conftest.py
test/test_camera_info.py
test/test_data/FileCameraZivid2M70.zfc
test/test_data/FileCameraZividOne.zfc
test/test_region_of_interest.py

The file `FileCameraZividOne.zfc` is on an old format that will no longer be supported in the upcoming SDK 2.10. It is also no longer included in the official sample data zip.
This commit updates the tests and instructions to use the new `FileCameraZivid2M70.zfc` instead.

Update file camera

---

setup.py

Currently, running `pip install .` in the repo root cannot be done multiple times. When running the second time, the developer is faced with a large error message. The solution is to delete the `_skbuild` directory that has popped up in the repo root, but the error message gives no hint that this may be the solution. This problem has confused both users and internal developers countless times.
This commit enabled easy repeated builds by overriding the build directory from the repo root to a random temporary directory. The way this is done is arguably a bit monkey-patchy, but to my knowledge there is no other way. This may be better in the modern in-progress re-implementation of `scikit-build` called `scikit-build-core`, which we could migrate to in the future.

Use temporary out-of-source build directory to enable repeated builds

---

continuous-integration/code-generation/generate_datamodels.sh

The script `docker_generate_datamodels.sh` has been broken since we started using virtual envs in the CI scripts a few weeks ago. Since `build.sh` installs `zivid` in a venv, `generate_datamodels.sh` would fail to find the package since it was not running in the same venv. This commit fixes this by making `generate_datamodels.sh` activate the CI venv set up by the previous steps. We only do this if there is no venv currently activated, because we still want developers to be able to run `generate_datamodels.sh` directly with their own venv.

Fix `docker_generate_datamodels.sh`

---

modules/zivid/experimental/calibration.py
src/Calibration/Calibration.cpp
test/calibration/test_intrinsics.py

SDK 2.10.0 introduces two overloads of the calibration.intrinsics API. One with settings and one with settings_2d. This commit adds support in the Python wrapper.

Add support for overloads of calibration.intrinsics

---

modules/_zivid/__init__.py
modules/zivid/__init__.py
modules/zivid/presets.py
samples/sample_presets.py
src/CMakeLists.txt
src/Presets.cpp
src/Wrapper.cpp
src/include/ZividPython/Presets.h
test/test_presets.py

The presets API added in Zivid SDK 2.9 allows the user to obtain settings presets that are fine tuned for each camera model for a number of different use-cases.
See samples/sample_presets.py for an example of how to use it.

Add python support for presets API

---

modules/zivid/experimental/calibration.py
src/InfieldCorrection/InfieldCorrection.cpp

This commit exposes two new functions from the experimental in-field correction C++ API:
1. A new overload of detect_feature_points that takes a Frame as an argument. The existing python function has been updated to support both a Camera (the previously supported argument type) and a Frame.
2. capture_calibration_board, which captures a calibration board with the correct settings and returns the frame.
Fixes ZIVID-6764

Add new in-field correction functions

---

continuous-integration/windows/setup.py

Windows CI tests are using older version of intel OpenCL CPU runtime. This older version is no longer supported in favor of intel OneAPI stack. This commit updates windows test to use OneAPI OpenCL CPU runtime.
Ubuntu tests were updated to use intel OneAPI OpenCL CPU runtime in commit
https://github.com/zivid/zivid-python/commit/b1be7bce34cb609a14cbbb1c192e391ae5f35dbe

Switch to modern OpenCL CPU runtime on Windows

---

continuous-integration/linux/platform-dependent/common.sh

The intel oneAPI repository was recently updated, which broke our install scripts:
```
The following packages have unmet dependencies:
intel-oneapi-runtime-compilers : Depends: intel-oneapi-runtime-openmp (= 2023.2.2-47) but 2024.0.0-49819 is to be installed
```
Looking at Intel's installation guide:
https://www.intel.com/content/www/us/en/docs/oneapi/installation-guide-linux/2024-0/apt.html Intel recommends installing a metapackage `intel-oneapi-runtime-libs`. This package now depends on `intel-oneapi-runtime-opencl-2024` and `intel-oneapi-runtime-compilers-2024`, so it seems like we should use these packages now.
Additionally, one of the packages is not declaring a dependency on `libxml2`, but does not work without it, so we have to install that manually as well.
MISC

CI: install 2024 versions of Intel OCL libraries

---

.github/workflows/main.yml
README.md
continuous-integration/linux/platform-dependent/ubuntu-23.10/setup.sh

We also make the linting job use this image, since we want that job to always use the latest supported Ubuntu.

Add Ubuntu 23.10 to CI test matrix

---

test/calibration/test_hand_eye.py
test/conftest.py

We noticed that unit-tests were failing when run with SDK 2.11. It turns out that we were not tearing down objects in the right order, and SDK 2.11 is less tolerance to such things.
This commit does two things to fix the unit-tests:
- Make sure that all fixtures that yield frames end up releasing those frames on teardown.
- Fix a test that created a new Application inside its code while also indirectly depending on the "application" fixture.

Fix unit-test fixture teardown

---

.gitignore
src/ReleasableArray2D.cpp
src/ReleasableImage.cpp
src/include/ZividPython/ReleasableArray2D.h

Removes code duplication in array2d and image class wrappers for Zivid::ColorRGBA and Zivid::ColorBGRA pixel formats. This helps when we add new pixel formats, for example, Zivid::ColorSRGB.

Remove some code duplication 

---

test/calibration/test_multi_camera.py

Commit 3a2f7658 fixed several issues with object lifetimes in the unit tests. However, one case was missed where a test depends on the application fixture but also creates its own Application instance. This caused an error when a new test was added that ran after the faulty test.

Fix unit test early Application teardown

---

modules/_zivid/__init__.py
modules/zivid/experimental/__init__.py
modules/zivid/experimental/_pixel_mapping.py
modules/zivid/experimental/calibration.py
src/CMakeLists.txt
src/Calibration/Calibration.cpp
src/PixelMapping.cpp
src/Wrapper.cpp
src/include/ZividPython/PixelMapping.h
test/experimental/test_pixel_mapping.py

Add wrapper for `zivid.calibration.pixel_mapping()` as well as `zivid.experimental.PixelMapping`

Add PixelMapping

---

.github/workflows/main.yml

Following Node.js 16 actions are deprecated: `actions/checkout@v3`, `actions/upload-artifact@v3`, `action-download-artifact@v3`, `actions/setup-python@v4` -
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
Update the actions to use the latest version.

CI - Update actions that use Node.js 16

---

modules/zivid/experimental/calibration.py

Commit 066edbae updated detect_feature_points to support giving either a Camera or a Frame as input. This left the docstring for InfieldCorrectionInput, which references the "version of detect_feature_points that takes a Camera argument" outdated.
This commit updates the wording to say "Camera or Frame".

Update docstring for InfieldCorrectionInput

---

modules/zivid/_calibration/detector.py
modules/zivid/calibration.py
src/Calibration/Calibration.cpp
test/calibration/test_calibration_board_detection.py
test/conftest.py
test/test_data/calibration_board.zfc
test/test_data/calibration_board_and_aruco_markers.zdf

This commit adds wrappers for new calibration board detection functions in the non-experimental `calibration` module. The following functions are added:
`detect_calibration_board` - This function can be used with either a Frame or Camera as input, and returns a DetectionResult.
`capture_calibration_board` - This function can be used to capture a frame with a Camera that later can be passed as input to the former function.

Add new non-experimental calibration board detection functions

---

.flake8
.pylintrc-tests
continuous-integration/code-generation/datamodel_frontend_generator.py
modules/_zivid/__init__.py
modules/zivid/__init__.py
modules/zivid/camera.py
modules/zivid/network_configuration.py
samples/sample_network_configuration.py
src/ReleasableCamera.cpp
src/Wrapper.cpp
src/include/ZividPython/ReleasableCamera.h
test/test_data/datamodels/NetworkConfiguration.yml
test/test_datamodel_serialize_from_serialized.py
test/test_network_configuration.py

This commit adds a wrapper for NetworkConfiguration datamodel as well as wrappers for new Camera class methods `network_configuration` and `apply_network_configuration`.

Add network configuration

---

src/SingletonApplication.cpp
src/include/ZividPython/Releasable.h

- Modify Singleton to accept constructor arguments for the object it manages
- Use Zivid::Detail::createApplicationForWrapper to construct the Application for the Python wrapper
Part of ZIVID-8484

Pass wrapper name when constructing Zivid::Application

---

.github/workflows/main.yml
README.md

Removes Ubuntu 23.10 and Fedora 39 as they are EOL. Adds Ubuntu 24.10 and Fedora 41

Update Linux distributions test matrix

---

src/include/ZividPython/DataModelWrapper.h

Previously we just hardcoded the Settings/Acquisition and Settings2D/Acquisition nodes. This commit makes it work for any uninstantiated node that is part of a datamodelList by recursively searching the datamodel.

Support wrapping uninstantiated datamodel nodes

---

pyproject.toml

There is a bug in the latest ninja package in PyPI, version 1.11.1.2, that causes ninja to call itself recursively until the system runs out of memory. This commit limits ninja to the previous version, 1.11.1.1, to prevent the issue.

Limit ninja version due to bug in the latest version

---

modules/zivid/frame.py
src/ReleasableFrame.cpp
src/include/ZividPython/ReleasableFrame.h
test/test_camera_capture.py
test/test_frame.py

Implement Frame.frame2d

---

modules/zivid/point_cloud.py
src/ReleasablePointCloud.cpp
src/include/ZividPython/ReleasablePointCloud.h
test/test_point_cloud.py

This is equivalent to C++ API `PointCloud::copyImageRGBA`, `PointCloud::copyImageBGRA` and `PointCloud::copyImageSRGB`. The function accepts a color format as an argument and returns `Image` object with the specified color format. This is helpful when saving a color image from point cloud data.

Implement point_cloud.copy_image() function

---

src/include/ZividPython/Releasable.h
src/include/ZividPython/ReleasableFrame.h

In d64366eb, the wrapper macros in Releasable.h were updated to unlock the GIL when calling into the SDK. However, it seems a couple of macros were missed in this commit. This meant that functions like `Frame::point_cloud` and `Camera::state` could not run in parallel.
This commit adds the GIL unlocking to the wrapper macros that were missed and also add the GIL unlock to one function that does not use wrapper macros.

Unlock GIL in all releasable class methods

---

modules/zivid/frame.py
modules/zivid/frame_2d.py
modules/zivid/image.py
modules/zivid/point_cloud.py
src/ReleasableFrame.cpp
src/ReleasableFrame2D.cpp
src/ReleasablePointCloud.cpp
src/include/ZividPython/Releasable.h
src/include/ZividPython/ReleasableFrame.h
src/include/ZividPython/ReleasableFrame2D.h
src/include/ZividPython/ReleasableImage.h
src/include/ZividPython/ReleasablePointCloud.h
src/include/ZividPython/Wrappers.h
test/assertions.py
test/test_frame.py
test/test_frame_2d.py
test/test_image_2d_bgra.py
test/test_image_2d_rgba.py
test/test_image_2d_srgb.py
test/test_point_cloud.py

This PR implements support for the [copy](https://docs.python.org/3/library/copy.html) module in `Frame`, `Frame2D` and `PointCloud` classes. Both shallow `copy` and `deepcopy` are supported.
Additionally, the `clone` method is added to be similar to the C++ API. This is also a deep copy.

Misc 2025 04 03 add copy and clone

---

samples/sample_update_firmware.py
src/Firmware.cpp

By default, `pybind11` will acquire python's global interpreter lock GIL before calling native code. Now `firmware.update` function accepts a user callback to log current firmware update status. It's quite common to use python's `print` function in this callback. Python's `print` function will also try to acquire GIL while we are holding the lock (default pybind11 behavior). This leads to a deadlock.
Since we do not call any python code in `Zivid::Firmware::update` function, there is no need to hold the GIL. Hence release the GIL before calling `Zivid::Firmware::update`. Then the user callback is free to acquire GIL and there is no deadlock.
Fixes ZIVID-10304

FW: Release GIL before calling native updateFirmware
