continuous-integration/linux/platform-dependent/arch/setup.sh, src/CameraRevision.cpp, src/Environment.cpp, src/Firmware.cpp, src/HDR.cpp, src/PointCloud.cpp, src/ReleasableCamera.cpp, src/ReleasableFrame.cpp, src/SingletonApplication.cpp, src/Version.cpp, src/Wrapper.cpp, src/include/ZividPython/CameraRevision.h, src/include/ZividPython/DataModelWrapper.h, src/include/ZividPython/Environment.h, src/include/ZividPython/Firmware.h, src/include/ZividPython/HDR.h, src/include/ZividPython/PointCloud.h, src/include/ZividPython/ReleasableCamera.h, src/include/ZividPython/ReleasableFrame.h, src/include/ZividPython/SingletonApplication.h, src/include/ZividPython/Version.h, src/include/ZividPython/Wrappers.h
Refer to commit messages for details
=> Delete cpp wrapper doc

.pylintrc-packaged-files, CMakeLists.txt, continuous-integration/linux/lint.sh, modules/_zivid/__init__.py, modules/zivid/__init__.py, modules/zivid/handeye.py, samples/sample_calibrate_eye_to_hand.py, setup.py, src/CMakeLists.txt, src/Calibrate.cpp, src/CalibrationResidual.cpp, src/CameraRevision.cpp, src/Checkerboard.cpp, src/Detector.cpp, src/HandEye.cpp, src/Pose.cpp, src/ReleasableCamera.cpp, src/ReleasableFrame.cpp, src/SingletonApplication.cpp, src/Wrapper.cpp, src/include/ZividPython/Calibrate.h, src/include/ZividPython/CalibrationResidual.h, src/include/ZividPython/Checkerboard.h, src/include/ZividPython/DataModelWrapper.h, src/include/ZividPython/Detector.h, src/include/ZividPython/HandEye.h, src/include/ZividPython/Matrix.h, src/include/ZividPython/Pose.h, src/include/ZividPython/Wrappers.h, test/test_hand_eye.py
This commit introduces 1.6.0's hand-eye calibration functionality,
allowing users to easily calibrate a camera with their robot.
Hand-eye calibration sample has been added.
=> Hand-eye calibration support

modules/_zivid/__init__.py, modules/zivid/__init__.py, modules/zivid/_make_enum_wrapper.py, modules/zivid/captureassistant.py, modules/zivid/hdr.py, samples/sample_captureassistant.py, src/AmbientLightFrequency.cpp, src/CMakeLists.txt, src/CaptureAssistant.cpp, src/HDR.cpp, src/SuggestSettingsParameters.cpp, src/Wrapper.cpp, src/include/ZividPython/AmbientLightFrequency.h, src/include/ZividPython/CaptureAssistant.h, src/include/ZividPython/SuggestSettingsParameters.h, src/include/ZividPython/Wrappers.h, test/test_captureassistant.py
This is initial commit. The commit adds:
1. AmbientLightFrequency
2. SuggestSettingsParammeters
3. suggestSettings
4. HDR::capture
=> Adding Capture Assistant support

README.md, setup.py
This version will be released to pypi, and introduces support for the Capture Assistant.
=> Version number is bumped to 0.9.3

test/test_capture_assistant.py
Test initializing max capture time
Test default ambient light frequency
=> Add capture assistant tests

README.md, continuous-integration/linux/platform-dependent/fedora-30/setup.sh, continuous-integration/linux/platform-dependent/ubuntu-16.04/setup.sh, continuous-integration/linux/platform-dependent/ubuntu-18.04/setup.sh, continuous-integration/windows/build.py, setup.py
- Updating to use SDK 1.8
- Updating zivid-python to 1.0.0
=> Bump to 1.0.0.1.8.0

samples/sample_capture_hdr.py
The dynamic range of new iris values is better for common scenes. These iris values are also in line with how to get the right exposure for good point clouds from the Zivid Academy.
Fixes #56
=> Change iris values in sample_capture_hdr.py

samples/sample_capture_from_file.py
Make the python sample consistent with the equivalent C++ sample
=> Change variable name in sample_capture_from_file.py

samples/sample_capture_assistant.py, samples/sample_capture_hdr.py
Make variable name consistent across python samples, in this case with sample_capture_hdr.py
This helps to simplify tutorials as they link to code snippets of different samples.
=> Change variable name in sample_capture_assistant,py

samples/sample_capture_assistant.py, samples/sample_capture_hdr.py
=> Pipeline test: PR to check if azure pipelines run

samples/sample_capture_2d.py
Make the python sample consistent with the equivalent C++ sample
Fixes #57
=> Change exposure values in sample_capture_2d.py

samples/sample_capture_assistant.py
Make the python sample consistent with the equivalent C++ sample
Fixes #55
=> Change ambient light frequency in sample_capture_assistant.py

LICENSE
=> #65 update copyright year

continuous-integration/linux/platform-dependent/arch/setup.sh
=> Downgrade opencl driver

samples/sample_calibrate_eye_to_hand.py, samples/sample_capture_from_file.py
- sample_calibrate_eye_to_hand.py: Did not run at all. Some calls were
not up to date with the new API. Also changed to using the capture
assistant, as this more consistently works for capturing checkerboards
at any range.
- sample_capture_from_file.py: Changed to "result.zdf" to be consistent
with all other samples.
=> Fix samples before 2.0 release

CMakeLists.txt, setup.py, src/CMakeLists.txt
2.6.1 is the latest version on conan. The changelog for pybind11
is at https://pybind11.readthedocs.io/en/stable/changelog.html
MISC
=> CMake: Update pybind11 to 2.6.1

.github/workflows/main.yml
Note how both commits in this PR are green (it now works with both `archlinux/base` and `archlinux/archlinux:base`), so the second commit is not strictly necessary. However, I added the second commit due to the discussion in #122 .
I'll let you Arch experts decide what's best.
=> Revert pr121 arch fix

README.md
This commit also makes variables for all zivid website and
knowledge base links and moves them at the bottom of the readme.
=> Update link for new KB

src/include/ZividPython/Releasable.h, src/include/ZividPython/Wrappers.h
Follow up from the internal teams thread
=> Fix crash in static globals

README.md
Add guiding for what to do when installing
zivid-python for Zivid SDK version older than
latest
MISC
=> readme: update guide for zivid-python versioning

README.md
All of our advanced samples are in the separate samples repo.  To increase its discoverability, it should be referenced in the zivid-python Readme file.
=> Readme: Reference separate zivid-python-samples repo

README.md
Editing and loading Settings via YML file instead of via the API is a pretty useful and common workflow, so it should be mentioned in the Quick Start section of the Readme.
=> Readme: Mention that one can load Settings from file

.github/workflows/main.yml, README.md, continuous-integration/linux/build-and-install-source-distribution.sh, continuous-integration/linux/build.sh, continuous-integration/linux/collect-and-check-artifacts.sh, continuous-integration/linux/create-source-distribution.sh, continuous-integration/linux/lint.sh, continuous-integration/linux/platform-dependent/common.sh, continuous-integration/linux/platform-dependent/fedora-34/setup.sh, continuous-integration/linux/platform-dependent/fedora-35/setup.sh, continuous-integration/linux/platform-dependent/fedora-36/setup.sh, continuous-integration/linux/platform-dependent/fedora-37/setup.sh, continuous-integration/linux/platform-dependent/ubuntu-18.04/setup.sh, continuous-integration/linux/platform-dependent/ubuntu-20.04/setup.sh, continuous-integration/linux/platform-dependent/ubuntu-22.04/setup.sh, continuous-integration/linux/platform-dependent/ubuntu-22.10/setup.sh, continuous-integration/linux/platform-dependent/ubuntu-23.04/setup.sh, continuous-integration/linux/setup.sh, continuous-integration/linux/test.sh, continuous-integration/linux/venv.sh
Definitely review commit-by-commit.
=> Modernize CI and supported OSs

modules/zivid/_calibration/detector.py, modules/zivid/_calibration/hand_eye.py, modules/zivid/_calibration/multi_camera.py, modules/zivid/camera.py, modules/zivid/experimental/calibration.py, modules/zivid/experimental/projection.py, modules/zivid/frame_2d.py, modules/zivid/image.py, modules/zivid/point_cloud.py, samples/sample_calibrate_eye_to_hand.py, samples/sample_capture.py, samples/sample_capture_2d.py, samples/sample_capture_assistant.py, samples/sample_capture_async.py, samples/sample_capture_from_file.py, samples/sample_capture_hdr.py, samples/sample_infield_correction.py, samples/sample_infield_verification.py
=> Fix bugs in samples and constructors

continuous-integration/windows/setup.py
Windows CI workflows have been failing due to a failure to clean up temporary directories. This commit adds a workaround that ignores these errors.
When we in the future are able to use Python 3.10 features, we can pass `ignore_cleanup_errors=True` to `tempfile.TemporaryDirectory()` instead.
=> Fix flakiness in Windows CI workflow setup
